name: CI/CD
on: 
  push

jobs:

  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
          channel: 'stable'
    - run: flutter pub get
    
    #lane: build number
    - name: Generate build number
      uses: einaregilsson/build-number@v2
      with:
        token: ${{secrets.github_token}}
  
   #lane: build develop
    - name: decode google-service.json
      env:
        GOOGLE_SERVICE_ANDROID_DEV: ${{ secrets.GOOGLE_SERVICE_ANDROID_DEV }}
      run: |
        echo $GOOGLE_SERVICE_ANDROID_DEV > ./android/app/google-services.json      

    - name: build
      run: |
        flutter build appbundle
        flutter build apk

    - name: Deploy
      uses: actions/upload-artifact@master
      with:
          name: apk-build
          path: build/app/outputs/bundle/release


    - name: Upload firebase
      if: contains(github.event.pull_request.labels.*.name, 'bug')
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
          appId: ${{secrets.FIREBASE_ANDROID_APPID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: tester-ci
          release_notes: "Build Android version $BUILD_NUMBER"
          file: build/app/outputs/apk/release/app-release.apk
    
    - name: Send a message to Chatwork
      if: contains(github.event.pull_request.labels.*.name, 'bug')
      run: |
        if [[ true ]];  then
              curl -X POST -H "X-ChatWorkToken: ${secrets.CHATWORK_TOKEN}" -d \
                "body=
                - Repository name: ABC
                - Author: ABC
                - Branch: ABC
                - Commit/pull request link: https://github.com
                - Build link: ABC
                " \
                "https://api.chatwork.com/v2/rooms/${secrets.CHATWORK_ROOM_ID}/messages"
            fi
    
    
