name: CI/CD
on: 
  release:
    types: [published, created, edited]
  push:
  pull_request: 

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
          channel: 'stable'
    - run: flutter pub get
    
   #lane: build develop
    - name: decode google-service.json
      env:
        GOOGLE_SERVICE_ANDROID_DEV: ${{ secrets.GOOGLE_SERVICE_ANDROID_DEV }}
      run: |
        echo $GOOGLE_SERVICE_ANDROID_DEV > ./android/app/google-services.json      

    - name: build
      run: |
        flutter build apk

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: apk-build
        path: build/app/outputs/apk/release
    
    
