on: 
  milestone:
    types: [closed]
name: Milestone Closure
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create Release Notes
      uses: docker://decathlon/release-notes-generator-action:1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FOLDER: temp_release_notes
        USE_MILESTONE_TITLE: "true"
    - name: Upload Release Notes to Wiki
      uses: docker://decathlon/wiki-page-creator-action:2.0.0
      env:
        ACTION_MAIL: tran.hoang.longb@sun-asterisk.com
        ACTION_NAME: longbth-1474
        GH_PAT: ${{ secrets.GH_PAT }}
        MD_FOLDER: temp_release_notes
        OWNER: longbth-1474
        REPO_NAME: https://github.com/longbth-1474/FlutterCI/
        SKIP_MD: README.md
